import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";//CSS página


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UNIENF", //Título página
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="description" content="Unienf Lagos"/>
        <meta name="keywords" content="curso de enfermagem, curso, região dos lagos, enfermagem"/>
        <meta name="author" content="Unienf Lagos"/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}